import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import localFont from "next/font/local";

const pixelifySans = localFont({
  src: [
    {
      path: "../../public/fonts/PixelifySans/PixelifySansRegular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/PixelifySans/PixelifySansBold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-pixelify-regular",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kourosh TorabiJafroudi",
  description: "Generated by Kourosh TorabiJafroudi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body
        className={`antialiased bg-red text-black dark:bg-black dark:text-white ${pixelifySans.variable}`}
      >
        <div className={`min-h-screen flex flex-col ${pixelifySans.variable}`}>
          <p>hellooo</p>

          {children}
        </div>
      </body>
    </html>
  );
}
